#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 11 17:42:27 2017

@author: pedrobcst
"""

def genPrimes():
    primes = []
    nextPrime = 1
    while True:
        nextPrime += 1
        append = True
        for p in primes:
            if(nextPrime % p == 0):
                append = False
                break
        if(append == True):
            primes.append(nextPrime)
            yield nextPrime


def genSpells():
    spell = [1,5,6,7,8,500]
    for k in spell:
        yield k
